[package]
name= "solana-tools"
version= "0.1.0"
edition= "2024"
description= "A collection of Rust scripts to automate common operations and processes on the Solana blockchain."
default-run= "sniper-trader"
autobins= false

[[bin]]
name= "sniper-trader"
path= "src/bin/sniperlauncher.rs"

[dependencies]
aws-config = "1.12.0"
aws-sdk-ec2 = "1.261.0"
aws-sdk-sts = "1.116.0"
base64 = "0.23.1"
bs58 = "0.5.1"
clap= { version = "4.6.6", features = ["derive"] }
colored = "3.1.1"
env_logger = "0.11.11"
log = "0.4.34"
num_cpus = "1.17.0"
simplelog = { version = "0.12.2", features = ["paris"] }
terminal_hyperlink = "0.1.0"
tokio = { version = "1.53.1", features = ["full"] }
