[package]
name= "sniper-trader"
version= "0.1.0"
edition= "2024"
description= "A Rust script to snipe recently graduated pump.fun coins using an RPC and Solana on-chain data."

[dependencies]
bs58 = "0.5.1"
clap= { version = "4.6.6", features = ["derive"] }
colored = "3.1.1"
env_logger = "0.11.11"
log = "0.4.34"
num_cpus = "1.17.0"
